stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker-compose -f docker-compose-development.yml build

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose-development.yml up -d
  only:
    - development

deploy-production:
  stage: deploy
  script:
    - docker-compose -f docker-compose-production.yml up -d
  only:
    - main

